# hide enchants in armour and weapons/tools, firework effects, books, and enchanted books
hide-item-meta: true
# hide potion information (except colour)
hide-potion-meta: true
# hide any potion effects a player might have, except for their particles
hide-potion-effects: true
# hide the true health of entities
hide-health: true